# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Hitchens - Custom"
license = "MIT"
licenselink = "https://github.com/pimoore/theme-tufte/blob/main/LICENSE.md"
description = "My version of the Hitchens Theme."
homepage = "https://github.com/pimoore/theme-hitchens"
tags = ["blog", "minimal"]
features = ["blog", ""]
min_version = 0.20

[author]
name = "Jered Benoit"
homepage = "https://jeredb.com"